INSERT INTO movies (title, year, director) VALUES
('Inception', 2010, 'Christopher Nolan'),
('Interstellar', 2014, 'Christopher Nolan'),
('The Dark Knight', 2008, 'Christopher Nolan'),
('Pulp Fiction', 1994, 'Quentin Tarantino'),
('Django Unchained', 2012, 'Quentin Tarantino'),
('Kill Bill', 2003, 'Quentin Tarantino'),
('The Matrix', 1999, 'Lana Wachowski and Lilly Wachowski'),
('Fight Club', 1999, 'David Fincher'),
('Seven', 1995, 'David Fincher'),
('Forrest Gump', 1994, 'Robert Zemeckis'),
('The Godfather', 1972, 'Francis Ford Coppola'),
('The Shawshank Redemption', 1994, 'Frank Darabont'),
('Titanic', 1997, 'James Cameron'),
('Avatar', 2009, 'James Cameron'),
('Parasite', 2019, 'Bong Joon-ho'),
('Spirited Away', 2001, 'Hayao Miyazaki'),
('The Lord of the Rings', 2001, 'Peter Jackson'),
('Gladiator', 2000, 'Ridley Scott'),
('Whiplash', 2014, 'Damien Chazelle'),
('La La Land', 2016, 'Damien Chazelle');