DROP TABLE IF EXISTS employee_projects;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  location text NOT NULL,
  annual_budget numeric(12,2) NOT NULL CHECK (annual_budget >= 0)
);

CREATE TABLE employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name text NOT NULL,
  last_name text NOT NULL,
  department_id bigint NOT NULL REFERENCES departments(id),
  title text NOT NULL,
  hire_date date NOT NULL,
  salary numeric(10,2) NOT NULL CHECK (salary > 0),
  performance_score integer CHECK (performance_score BETWEEN 1 AND 5),
  manager_id bigint REFERENCES employees(id),
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  department_id bigint NOT NULL REFERENCES departments(id),
  start_date date NOT NULL,
  end_date date,
  budget numeric(12,2) NOT NULL CHECK (budget >= 0),
  status text NOT NULL CHECK (status IN ('active', 'completed', 'paused', 'cancelled'))
);

CREATE TABLE employee_projects (
  employee_id bigint NOT NULL REFERENCES employees(id),
  project_id bigint NOT NULL REFERENCES projects(id),
  role text NOT NULL,
  hours_per_week integer NOT NULL CHECK (hours_per_week BETWEEN 1 AND 40),
  assigned_at date NOT NULL,
  PRIMARY KEY (employee_id, project_id)
);
